name: flutter_image_ppicker
description: A new Flutter application.

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.4.5
  image_cropper: ^0.0.4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

assets:
  - assets/photo_camera.png